BaseUrl: "https://yet.unresolved.xyz/"
LanguageCode: "ja-jp"
Title: "Unresolved"

Params:
  Author: "Daisuke Tsuji"
  GoogleAnalyticsUserID: "UA-55005303-1"
  SectionRobots:
    diary: "noindex,nofollow"

Indexes:
  tag: "tags"

permalinks:
  technology: /blog/:year/:month/:day/:slug/
  book: /blog/:year/:month/:day/:slug/
  diary: /blog/:year/:month/:day/:slug/

MetadataFormat: "yaml"
HasCJKLanguage: true
disqusShortname: "unresolved"

